// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbRP7uCmCx7Rs4Q-aUQnz11Fg-vJUVhdY',
    appId: '1:784514623715:android:3126a4e9daf401a5b4bdd6',
    messagingSenderId: '784514623715',
    projectId: 'poke-master-d2ef3',
    storageBucket: 'poke-master-d2ef3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCefz7wxfRknk5DxY9uxIwmViwdCUgegYA',
    appId: '1:784514623715:ios:3adf7276a660f96db4bdd6',
    messagingSenderId: '784514623715',
    projectId: 'poke-master-d2ef3',
    storageBucket: 'poke-master-d2ef3.firebasestorage.app',
    iosBundleId: 'com.ynghk.pokemaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCefz7wxfRknk5DxY9uxIwmViwdCUgegYA',
    appId: '1:784514623715:ios:3adf7276a660f96db4bdd6',
    messagingSenderId: '784514623715',
    projectId: 'poke-master-d2ef3',
    storageBucket: 'poke-master-d2ef3.firebasestorage.app',
    iosBundleId: 'com.ynghk.pokemaster',
  );

}